project:
  type: book

book:
  title: "Multi-Word Representations in Minds and Models: Investigating Storage Mechanisms in Humans and Large Language Models"
  author: "Zachary Nicholas Houghton"
  date: "11/25/2024"
  chapters:
    - index.qmd
    - Chapters/Introduction/introduction.qmd
    - Chapters/references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    keep-tex: false
    link-citations: true
    colorlinks: false
    classoption: nottoc
    lot: true
    lof: true
    geometry:
      - left=2in
      - right=2in
      - marginparwidth=1.5in
      - twoside=true
    include-in-header: 
      text: | 
        \usepackage{tocbibind}
editor: visual

    
    