project:
  type: book
  output-dir: _book

book:
  title: "Multi-Word Representations in Minds and Models"
  subtitle: "Investigating the Storage of Multi-Word Phrases in Humans and Large Language Models"
  author:
    - name: "Zachary Nicholas Houghton"
      orcid: "0000-0002-0320-8881"
      degree: "Linguistics"
      affiliations:
        - name: "University of California, Davis"
          department: "Department of Linguistics"
  

  chapters:
    #- Chapters/acknowledgements.qmd
    #- Chapters/abstract.qmd
    - index.qmd
    - Chapters/Introduction/introduction.qmd
    - Chapters/Compound Nouns/staub_rep_ext.qmd
    - Chapters/Recognizability/Write-up/quarto-writeup.qmd
    - Chapters/LLM Ordering Prefs/Writeup/writeup-llm-ordering-prefs.qmd
    - Chapters/LLM Storage/Writeup/writeup-llm-storage.qmd
    - Chapters/frequency-dependent preference extremity/frequency-dependent preference extremity.qmd
    - Chapters/conclusion.qmd
    - Chapters/references.qmd
  appendices: 
    - Chapters/appendix_model_results.qmd
    - Chapters/appendix_llm_individual_constraints.qmd
    - Chapters/appendix_llm_stimuli.qmd
  
  output-file: houghton_dissertation
  
degree: "Linguistics"
dissertation_name: "Dissertation Name"
author_name: "ZACHARY NICHOLAS HOUGHTON"
field_of_study: "Linguistics"
committee_member_1: "Dr. Emily Morgan, Chair"
committee_member_2: "Dr. Masoud Jasbi"
committee_member_3: "Dr. Fernanda Ferreira"
submission_year: "2025"


format:
  html:
    theme: cosmo

  pdf:
    template-partials:
      - before-body.tex
      #- toc.tex
    latex-engine: xelatex 
    documentclass: scrreport   # LaTeX document class for professional formatting
    number-depth: 3
    # Caption Formatting
    fig-cap-location: top      # Figure captions above
    tbl-cap-location: top      # Table captions above
    fig-pos: 'htbp'        # Let LaTeX decide where to place the figures
    fig-align: center       # Centering figures
    keep-tex: true             # Optional: for debugging TeX
    latex-output: houghton_dissertation.tex
    # Font Settings
    fontsize: 12pt
    mainfont: "Crimson"        # Primary text font
    CJKmainfont: "Noto Serif KR"  # Font for Korean text
    link-citations: true       # Enable hyperlinked citations
    colorlinks: false          # Disable colored hyperlinks
    toc: true
    toc-depth: 3
    #toc-title: "Table of Contents"
    lot: true                  # Enable List of Tables
    lof: true                  # Enable List of Figures

    # Page Layout #Not supposed to use geometry for koma apparently
    geometry:
      - left=1in
      - right=1in
      - top=1in
      - bottom=1in

    include-in-header: 
      - include-in-header.tex

  docx:
    number-sections: true
    number-depth: 3
    toc-title: Table of Contents
    toc: true
    toc-depth: 3
    reference-doc: reference.docx
    filters: 
      - chapter-prefix.lua
      - chapter_rename_with_pagebreaks.lua
        
bibliography: references.bib          
csl: apa.csl
editor: visual
