project:
  type: book

book:
  title: "dissertation_writeup"
  author: "Norah Jones"
  date: "11/25/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

