project:
  type: book

book:
  title: "Multi-Word Representations in Minds and Models"
  subtitle: "Investigating the Storage of Multi-Word Phrases in Humans and Large Language Models"
  author:
    - name: "Zachary Nicholas Houghton"
      orcid: "0000-0002-0320-8881"
      degree: "Linguistics"
      affiliations:
        - name: "University of California, Davis"
          department: "Department of Linguistics"
  chapters:
    - index.qmd
    - Chapters/Introduction/introduction.qmd
    - Chapters/Compound Nouns/staub_rep_ext.qmd
    - Chapters/Recognizability/Write-up/quarto-writeup.qmd
    - Chapters/references.qmd
  
  output-file: houghton_dissertation
  #image: dissertation_image.png
  
degree: "Linguistics"
dissertation_name: "Dissertation Name"
author_name: "Zachary Nicholas Houghton"
field_of_study: "Linguistics"
committee_member_1: "Dr. Emily Morgan, Chair"
committee_member_2: "Dr. Masoud Jasbi"
committee_member_3: "Dr. Fernanda Ferreira"
submission_year: "2025"


format:
  html:
    theme: cosmo

  pdf:
    template-partials:
      - before-body.tex
    latex-engine: lualatex 
    documentclass: scrreprt   # LaTeX document class for professional formatting

    number-depth: 2
    # Caption Formatting
    fig-cap-location: top      # Figure captions above
    tbl-cap-location: top      # Table captions above
    fig-pos: 'htbp'        # Let LaTeX decide where to place the figures
    #fig-width: 6            # Set a reasonable default width
    #fig-height: 6           # Or set a safe height for your figure
    fig-align: center       # Centering figures
    #out.width: '\\linewidth'  # Use LaTeX defaults
    #out.height: ''           # This explicitly avoids setting height
    keep-tex: true             # Optional: for debugging TeX
    # Font Settings
    fontsize: 12pt
    mainfont: "Crimson"        # Primary text font
    CJKmainfont: "Noto Serif KR"  # Font for Korean text

    # Citations & References
    link-citations: true       # Enable hyperlinked citations
    colorlinks: false          # Disable colored hyperlinks
    toc: true
    toc-depth: 3
    toc-title: "Table of contents"
    lot: true                  # Enable List of Tables
    lof: true                  # Enable List of Figures

    # Page Layout
    geometry:
      - left=1in
      - right=1in
      - top=1in
      - bottom=1in

    include-in-header: 
      - include-in-header.tex

echo: false
warning: false
message: false
        
bibliography: references.bib          
csl: apa.csl
editor: visual
