```{r, echo = F}
library(tidyverse)
library(brms)
library(here)
library(ggh4x)

corpus = read_csv(paste0(here("Chapters/LLM Ordering Prefs/Data"), '/nonce_binoms.csv'))

combined_df = read_csv(paste0(here("Chapters/LLM Ordering Prefs/Data"), "/combined_df.csv"))

checkpoint_tokens_key = combined_df %>%
  group_by(checkpoint) %>%
  slice_head(n=1) %>%
  select(checkpoint, num_tokens, n_billion_tokens)

fixefs_m3 = read_csv(paste0(here("Chapters/LLM Ordering Prefs/Data"), "/fixefs_m3.csv"))

```

# Individual Constraints at Each Checkpoint {#sec-individual-constraints-at-each-checkpoint .appendix}

```{r, echo = F, message = F}
#| label: tbl-exp2m2
#| tbl-cap: "Model results examining the effect of each individual constraint on LogOdds(AandB)."

#table 1
fixefsexp2m3 = fixefs_m3 %>%
  left_join(checkpoint_tokens_key) %>%
  #filter(Parameter == 'GenPref') %>%
  filter(n_billion_tokens %in% c(0, 2, 41, 209, 419, 838, 1677)) %>%
  arrange(n_billion_tokens) %>%
  mutate_if(is.numeric,
            formatC,
            format = 'f',
            digits = 3) %>%
  select(-n_billion_tokens, -checkpoint) 


fixefsexp2m3 = fixefsexp2m3[,c('Parameter', 'num_tokens', 'Estimate', 'Est.Error', 'Q2.5', 'Q97.5')]

knitr::kable(fixefsexp2m3, booktabs = T)
```
