# Conclusion

The aim of this dissertation was to provide an in-depth examination of holistic multi-word storage. In Chapter 2, we examined whether holistically stored items can overcome local implausibility effects and found that they can't. In Chapter 3, we found that holistically stored items can lose part of their internal structure. In Chapter 4, we demonstrated that large language models can capture the tradeoff between item-specific knowledge and abstract preferences that we see in humans. Further, in Chapter 5 we demonstrated that large language models provide predictions about the representations of holistically stored items and how they may vary from their compositional representations as a function of frequency. Finally, in Chapter 6 we demonstrated that positing holistic storage can account for certain features of language change, mainly frequency-dependent preference extremity.

I have also argued that theories of processing and learning must account for multi-word storage. Many processing theories still assume, either explicitly or implicitly, that each sentence is broken down into individual words that are then combined using knowledge of the grammar. However, positing multi-word holistic storage will lead to a new, rich set of predictions and questions.

In this section, we bring our results into context with some of the bigger picture questions we asked in the beginning. We then highlight the contributions to language learning, language processing, and examine some of the interesting questions that come out of this work.

## Revisiting our questions

At the beginning of this dissertation, I posited three questions: 1) what factors determine whether a phrase is stored holistically or generated compositionally? 2) What are the processing consequences for holistic storage? And 3) How are holistically stored phrases represented? In this section, I return to each of the questions and explore what we've learned. I will then explore future questions and what their answers may tell us.

With respect to our first question, in this dissertation I have presented evidence that both frequency and predictability drive storage. I have shown, for example, that *up* is harder for participants to recognize in high-frequency or high-predictability phrases than in medium-frequency or medium-predictability phrases. I have also shown that models of learning (large language models) predict that learners rely on item-specific knowledge for binomials that they have experienced before (Chapter 4), especially those that are high-frequency. On the other hand, they also rely on abstract preferences for binomials that they have not experienced before (similar to humans). Further, I have demonstrated that they also predict that the representations of high-frequency binomials diverge more from their compositional representations than low-frequency binomials (Chapter 5).

With respect to our second question, in addition to frequency and predictability effects on storage, I have also demonstrated that holistically stored representations cannot be accessed after hearing only the first word in the phrase. For example, the results of Chapter 2 suggested that readers cannot overcome the local implausibility at the first noun in a compound noun, even if that compound noun is frequent or predictable. If readers were able to access the second noun in the compound, the local implausibility would have been eliminated, reducing the increase in processing difficulty. In other words, participants don't access the representation of the phrase until they have enough acoustic information to disambiguate between the phrase and its competitors.

With respect to our third question, I have provided evidence that holistically stored phrases lose at least some of their internal structure. For example, in Chapter 3 I showed that *up* becomes easier to recognize as frequency and/or predictability increases, until reaching the most frequent and/or most predictable items, where recognition of *up* becomes more difficult. I argued that this is evidence that they lost some amount of their internal structure. I further argued that this suggests that the representation of the phrase competes with the representations of the individual words, causing a slowdown in recognition time for the individual words that comprise the phrase. In addition to demonstrating the representations of holistically stored items, these results also demonstrate the importance of expanding current areas of the literature, such as the word-recognition literature, to include the topic of multi-word holistic storage.

Finally, in this dissertation I have argued that holistic storage arises naturally as a function of our learning mechanisms. Multi-word storage is a natural product of learning to chunk frequent and/or predictable events together. However, what are the implications of this for language learning and processing more broadly? In the next few sections I discuss the implications of these results with respect to learning and processing.

## Language Learning

Holistic storage, as I stated before, arises naturally out of learning mechanisms. For example, babies are faced with the task of segmenting the speech stream into individual words and phrases and evidence suggests they leverage the statistics of the language, such as transitional probabilities, to accomplish this [@saffranStatisticalLearning8MonthOld1996]. This naturally results in high-predictability phrases being segmented out as individual units.

Additionally, holistic storage sheds light on other learning phenomena. For example, @harmonPuttingOldTools2017 examined what factors lead learners to extend a form to a novel meaning. They used an artificial language learning task where one of the suffixes was more frequent than the other. They then tested the learners in a production and forced-choice task. They found that when learners had to produce a novel meaning, they produced the frequent suffix more frequently than the infrequent suffix, and even more so than when the meaning they wished to express was familiar (i.e., encountered in training). Additionally, they found that when both forms were made accessible (via the form-choice task, where they were asked to choose between the two suffixes), this preference disappeared. They argued that this was due to increased accessibility.

Holistic storage makes an interesting prediction with respect to the results from @harmonPuttingOldTools2017. Specifically, in Chapter 3 we demonstrated that holistically stored items can lose part of their internal representation. This result suggests that in cases where the multi-morphemic word is stored instead of generated, the learner may not semantically extend the suffix to a novel meaning if the stem is also novel, even if it is very accessible. This is because the learner would have to infer which part of the meaning is attributed to the suffix, which they would be unable to do if the representation for the stem and suffix fuse together. In other words, the results of the dissertation suggest that parts of holistically stored items that have lost their internal representation may be less likely to be extended to novel contexts without the other subparts of the holistically stored item.

One way to test this prediction is to manipulate the type frequency of the suffix (i.e., how many different stems it appears with). That is, in @harmonPuttingOldTools2017 the frequent form had both a greater token frequency (appeared a greater number of times) and a greater type frequency (it appeared with a larger number of stems). In other words, the stem was not particularly predictable of the frequent suffix. However, if type frequency were to be reduced then even though the form should be equally as accessible (overall frequency is not changing), the stem would be very predictable of the suffix, and may be stored holistically. If this is the case then the results from Chapter 2 suggest that the internal representation of the suffix may degrade, and the suffix may be less likely to be extended by the learner to novel contexts.

Holistic storage also makes interesting predictions about how people may learn abstract knowledge to begin with. For example, in Chapter 4 we demonstrated that large language models account for the phenomenon wherein people rely on item-specific knowledge for binomials they have encountered before, but rely on abstract preferences (e.g., a preference for short words before long words) for binomials they have not encountered before. If high-frequency items are stored holistically, then they may contribute less to these abstract preferences than items that are composed each time, because they may fuse together losing part of their internal structure.

Another way to frame this is that the learner, when encountering a binomial, must learn what preferences are unique to the binomial and what are more general patterns of binomial orderings. For example, *bread and butter* is preferred over *butter and bread*, however if the representation fuses together, then even though *bread and butter* is overwhelmingly more frequent than *butter and bread*, it may not contribute as much to the abstract preference of short-before-long than lower-frequency items do. That is, the learner may attribute that feature to the specific item, as opposed to learning it as an abstract preference of all binomials. We look forward to testing this prediction using language models [by using methods such as those in @misraLanguageModelsLearn2024 and @yaoBothDirectIndirect2025] in future work.

In addition to language learning, however, the present dissertation also has implications for language processing as well.

## Language Processing

The present dissertation also has implications for language processing. For example, we have shown that both frequency and predictability drive storage. However, are frequency and predictability two measurements of the same underlying cognitive process (e.g., accessibility)? It is possible frequency effects are a result of automatization while predictability effects may be a consequence of learning. For example, as people perform a sequence of motor actions more often (i.e., as the sequence of motor actions becomes more frequent), humans become able to perform the sequence more quickly and more fluidly [@sosnik2004whenpracticeleads]. It is possible that frequency effects on storage are a result of a similar process: as people use a phrase more often, it becomes more automatic and this results in it being stored separately.

On the other hand, learners are not simply sensitive to how frequent a cue occurs with an outcome, but also to how predictive a cue is of an outcome [e.g., @ramscarChildrenValueInformativity2013]. Thus, it is possible that rather than automatization, predictability drives storage because predictable things are simply learned as a single chunk. Interestingly, this makes a novel prediction for language learning as well: frequency may lead to storage over time, as the item becomes more automatic, while predictability may lead to storage at the onset because it is learned as a single chunk.

Additionally, very few theories of processing expressly account for multi-word storage [c.f., fragment grammar theories; e.g., @odonnellFragmentGrammarsExploring2009; @morganFormalizingConstructionGrammar]. However, positing multi-word storage generates new interesting questions for the processing literature. For example, storing the phrase *I don't know* holistically does not preclude the learner from generating the phrase compositionally. In fact, the learner is almost certainly still capable of generating the phrase compositionally. Thus, in what cases do humans access the holistic representation instead of generating it compositionally? Further, does this vary as a function of task (e.g., production vs perception)? For example, it seems more likely that someone would access the phrase holistically in production than perception, because in production the speaker has a specific meaning they wish to convey. However, in perception it is less clear. For example, when listening to a sentence, the listener must by definition listen in a temporally linear manner (i.e., word-by-word). As such, does the listener wait until hearing the phrase before accessing any of the parts? Despite the difficulty of this question, it is an important one for the processing literature to address.

Finally, are holistically stored phrases stored and processed in the same way as lexical items? In other words, is holistic storage the same thing as lexical storage? This is an interesting question because holistic storage makes many novel predictions with respect to lexical processing. For example, if lexical items compete for activation with other lexical items [@mcclelland1984], then positing the holistic storage of phrases suggest that they may compete, not only with other phrases, but with word-level representations as well.
